### ISSUE TITLE
`nest_by` should allow for multiple arguments

### ISSUE THREAD

**Issue by koaning** [koaning/lazylines#1]
I want to be able to do stuff like this:

```python
from lazylines import read_jsonl

read_jsonl("examples.jsonl").nest_by("_input_hash", "_task_hash").show(1)
```

This would also mean that `unnest` would need to be updated.

**Comment by koaning** [comment]
When working on this, it'd be good to ensure stuff like this works again. 

```python
from lazylines import read_jsonl

read_jsonl("mult_annotator_test.jsonl").nest_by("_input_hash").unnest("_input_hash").show(1)
```

Right now it gives this error. 

```
Traceback (most recent call last):
  File "prepr.py", line 3, in <module>
    read_jsonl("mult_annotator_test.jsonl").nest_by("_input_hash").unnest("_input_hash").show(1)
  File "/home/vincent/Development/prodigy-demos/venv/lib/python3.8/site-packages/lazylines/__init__.py", line 152, in show
    pprint.pprint(next(stream_copy))
  File "/home/vincent/Development/prodigy-demos/venv/lib/python3.8/site-packages/lazylines/__init__.py", line 126, in new_gen
    for value in item[key]:
TypeError: 'int' object is not iterable
```

I also think that it might be better to have `unnest` not take any arguments. The `subset` key merely needs to be exploded.
